services:
  mail-monitor:
    image: wsng911/mail-code-monitor:Mail-code-to-TG
    container_name: mail-monitor
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
